# .github/workflows/firebase-hosting.yml

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ✅ Add this step to install dependencies
      - name: Install dependencies
        run: npm install

      # 🔧 Now run the build
      - name: Build project
        run: npm run build

      # 🚀 Firebase Hosting deploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MINIMAL_INVENTORY_PROJECT }}
          channelId: live
          projectId: minimal-inventory-project
